
import { Surah } from './types';

export const SURAHS: Surah[] = [
  { id: 1, name: "الفاتحة", englishName: "Al-Fatihah", versesCount: 7, revelationType: 'Meccan' },
  { id: 2, name: "البقرة", englishName: "Al-Baqarah", versesCount: 286, revelationType: 'Medinan' },
  { id: 3, name: "آل عمران", englishName: "Al-Imran", versesCount: 200, revelationType: 'Medinan' },
  { id: 4, name: "النساء", englishName: "An-Nisa", versesCount: 176, revelationType: 'Medinan' },
  { id: 5, name: "المائدة", englishName: "Al-Ma'idah", versesCount: 120, revelationType: 'Medinan' },
  { id: 6, name: "الأنعام", englishName: "Al-An'am", versesCount: 165, revelationType: 'Meccan' },
  { id: 7, name: "الأعراف", englishName: "Al-A'raf", versesCount: 206, revelationType: 'Meccan' },
  { id: 8, name: "الأنفال", englishName: "Al-Anfal", versesCount: 75, revelationType: 'Medinan' },
  { id: 9, name: "التوبة", englishName: "At-Tawbah", versesCount: 129, revelationType: 'Medinan' },
  { id: 10, name: "يونس", englishName: "Yunus", versesCount: 109, revelationType: 'Meccan' },
  { id: 11, name: "هود", englishName: "Hud", versesCount: 123, revelationType: 'Meccan' },
  { id: 12, name: "يوسف", englishName: "Yusuf", versesCount: 111, revelationType: 'Meccan' },
  { id: 13, name: "الرعد", englishName: "Ar-Ra'd", versesCount: 43, revelationType: 'Medinan' },
  { id: 14, name: "إبراهيم", englishName: "Ibrahim", versesCount: 52, revelationType: 'Meccan' },
  { id: 15, name: "الحجر", englishName: "Al-Hijr", versesCount: 99, revelationType: 'Meccan' },
  { id: 16, name: "النحل", englishName: "An-Nahl", versesCount: 128, revelationType: 'Meccan' },
  { id: 17, name: "الإسراء", englishName: "Al-Isra", versesCount: 111, revelationType: 'Meccan' },
  { id: 18, name: "الكهف", englishName: "Al-Kahf", versesCount: 110, revelationType: 'Meccan' },
  { id: 19, name: "مريم", englishName: "Maryam", versesCount: 98, revelationType: 'Meccan' },
  { id: 20, name: "طه", englishName: "Ta-Ha", versesCount: 135, revelationType: 'Meccan' },
  { id: 21, name: "الأنبياء", englishName: "Al-Anbiya", versesCount: 112, revelationType: 'Meccan' },
  { id: 22, name: "الحج", englishName: "Al-Hajj", versesCount: 78, revelationType: 'Medinan' },
  { id: 23, name: "المؤمنون", englishName: "Al-Mu'minun", versesCount: 118, revelationType: 'Meccan' },
  { id: 24, name: "النور", englishName: "An-Nur", versesCount: 64, revelationType: 'Medinan' },
  { id: 25, name: "الفرقان", englishName: "Al-Furqan", versesCount: 77, revelationType: 'Meccan' },
  { id: 26, name: "الشعراء", englishName: "Ash-Shu'ara", versesCount: 227, revelationType: 'Meccan' },
  { id: 27, name: "النمل", englishName: "An-Naml", versesCount: 93, revelationType: 'Meccan' },
  { id: 28, name: "القصص", englishName: "Al-Qasas", versesCount: 88, revelationType: 'Meccan' },
  { id: 29, name: "العنكبوت", englishName: "Al-Ankabut", versesCount: 69, revelationType: 'Meccan' },
  { id: 30, name: "الروم", englishName: "Ar-Rum", versesCount: 60, revelationType: 'Meccan' },
  { id: 31, name: "لقمان", englishName: "Luqman", versesCount: 34, revelationType: 'Meccan' },
  { id: 32, name: "السجدة", englishName: "As-Sajdah", versesCount: 30, revelationType: 'Meccan' },
  { id: 33, name: "الأحزاب", englishName: "Al-Ahzab", versesCount: 73, revelationType: 'Medinan' },
  { id: 34, name: "سبأ", englishName: "Saba", versesCount: 54, revelationType: 'Meccan' },
  { id: 35, name: "فاطر", englishName: "Fatir", versesCount: 45, revelationType: 'Meccan' },
  { id: 36, name: "يس", englishName: "Ya-Sin", versesCount: 83, revelationType: 'Meccan' },
  { id: 37, name: "الصافات", englishName: "As-Saffat", versesCount: 182, revelationType: 'Meccan' },
  { id: 38, name: "ص", englishName: "Sad", versesCount: 88, revelationType: 'Meccan' },
  { id: 39, name: "الزمر", englishName: "Az-Zumar", versesCount: 75, revelationType: 'Meccan' },
  { id: 40, name: "غافر", englishName: "Ghafir", versesCount: 85, revelationType: 'Meccan' },
  { id: 41, name: "فصلت", englishName: "Fussilat", versesCount: 54, revelationType: 'Meccan' },
  { id: 42, name: "الشورى", englishName: "Ash-Shura", versesCount: 53, revelationType: 'Meccan' },
  { id: 43, name: "الزخرف", englishName: "Az-Zukhruf", versesCount: 89, revelationType: 'Meccan' },
  { id: 44, name: "الدخان", englishName: "Ad-Dukhan", versesCount: 59, revelationType: 'Meccan' },
  { id: 45, name: "الجاثية", englishName: "Al-Jathiyah", versesCount: 37, revelationType: 'Meccan' },
  { id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", versesCount: 35, revelationType: 'Meccan' },
  { id: 47, name: "محمد", englishName: "Muhammad", versesCount: 38, revelationType: 'Medinan' },
  { id: 48, name: "الفتح", englishName: "Al-Fath", versesCount: 29, revelationType: 'Medinan' },
  { id: 49, name: "الحجرات", englishName: "Al-Hujurat", versesCount: 18, revelationType: 'Medinan' },
  { id: 50, name: "ق", englishName: "Qaf", versesCount: 45, revelationType: 'Meccan' },
  { id: 51, name: "الذاريات", englishName: "Adh-Dhariyat", versesCount: 60, revelationType: 'Meccan' },
  { id: 52, name: "الطور", englishName: "At-Tur", versesCount: 49, revelationType: 'Meccan' },
  { id: 53, name: "النجم", englishName: "An-Najm", versesCount: 62, revelationType: 'Meccan' },
  { id: 54, name: "القمر", englishName: "Al-Qamar", versesCount: 55, revelationType: 'Meccan' },
  { id: 55, name: "الرحمن", englishName: "Ar-Rahman", versesCount: 78, revelationType: 'Medinan' },
  { id: 56, name: "الواقعة", englishName: "Al-Waqi'ah", versesCount: 96, revelationType: 'Meccan' },
  { id: 57, name: "الحديد", englishName: "Al-Hadid", versesCount: 29, revelationType: 'Medinan' },
  { id: 58, name: "المجادلة", englishName: "Al-Mujadilah", versesCount: 22, revelationType: 'Medinan' },
  { id: 59, name: "الحشر", englishName: "Al-Hashr", versesCount: 24, revelationType: 'Medinan' },
  { id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", versesCount: 13, revelationType: 'Medinan' },
  { id: 61, name: "الصف", englishName: "As-Saff", versesCount: 14, revelationType: 'Medinan' },
  { id: 62, name: "الجمعة", englishName: "Al-Jumu'ah", versesCount: 11, revelationType: 'Medinan' },
  { id: 63, name: "المنافقون", englishName: "Al-Munafiqun", versesCount: 11, revelationType: 'Medinan' },
  { id: 64, name: "التغابن", englishName: "At-Taghabun", versesCount: 18, revelationType: 'Medinan' },
  { id: 65, name: "الطلاق", englishName: "At-Talaq", versesCount: 12, revelationType: 'Medinan' },
  { id: 66, name: "التحريم", englishName: "At-Tahrim", versesCount: 12, revelationType: 'Medinan' },
  { id: 67, name: "الملك", englishName: "Al-Mulk", versesCount: 30, revelationType: 'Meccan' },
  { id: 68, name: "القلم", englishName: "Al-Qalam", versesCount: 52, revelationType: 'Meccan' },
  { id: 69, name: "الحاقة", englishName: "Al-Haqqah", versesCount: 52, revelationType: 'Meccan' },
  { id: 70, name: "المعارج", englishName: "Al-Ma'arij", versesCount: 44, revelationType: 'Meccan' },
  { id: 71, name: "نوح", englishName: "Nuh", versesCount: 28, revelationType: 'Meccan' },
  { id: 72, name: "الجن", englishName: "Al-Jinn", versesCount: 28, revelationType: 'Meccan' },
  { id: 73, name: "المزمل", englishName: "Al-Muzzammil", versesCount: 20, revelationType: 'Meccan' },
  { id: 74, name: "المدثر", englishName: "Al-Muddaththir", versesCount: 56, revelationType: 'Meccan' },
  { id: 75, name: "القيامة", englishName: "Al-Qiyamah", versesCount: 40, revelationType: 'Meccan' },
  { id: 76, name: "الإنسان", englishName: "Al-Insan", versesCount: 31, revelationType: 'Medinan' },
  { id: 77, name: "المرسلات", englishName: "Al-Mursalat", versesCount: 50, revelationType: 'Meccan' },
  { id: 78, name: "النبأ", englishName: "An-Naba", versesCount: 40, revelationType: 'Meccan' },
  { id: 79, name: "النازعات", englishName: "An-Nazi'at", versesCount: 46, revelationType: 'Meccan' },
  { id: 80, name: "عبس", englishName: "Abasa", versesCount: 42, revelationType: 'Meccan' },
  { id: 81, name: "التكوير", englishName: "At-Takwir", versesCount: 29, revelationType: 'Meccan' },
  { id: 82, name: "الانفطار", englishName: "Al-Infitar", versesCount: 19, revelationType: 'Meccan' },
  { id: 83, name: "المطففين", englishName: "Al-Mutaffifin", versesCount: 36, revelationType: 'Meccan' },
  { id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", versesCount: 25, revelationType: 'Meccan' },
  { id: 85, name: "البروج", englishName: "Al-Buruj", versesCount: 22, revelationType: 'Meccan' },
  { id: 86, name: "الطارق", englishName: "At-Tariq", versesCount: 17, revelationType: 'Meccan' },
  { id: 87, name: "الأعلى", englishName: "Al-A'la", versesCount: 19, revelationType: 'Meccan' },
  { id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", versesCount: 26, revelationType: 'Meccan' },
  { id: 89, name: "الفجر", englishName: "Al-Fajr", versesCount: 30, revelationType: 'Meccan' },
  { id: 90, name: "البلد", englishName: "Al-Balad", versesCount: 20, revelationType: 'Meccan' },
  { id: 91, name: "الشمس", englishName: "Ash-Shams", versesCount: 15, revelationType: 'Meccan' },
  { id: 92, name: "الليل", englishName: "Al-Layl", versesCount: 21, revelationType: 'Meccan' },
  { id: 93, name: "الضحى", englishName: "Ad-Duha", versesCount: 11, revelationType: 'Meccan' },
  { id: 94, name: "الشرح", englishName: "Ash-Sharh", versesCount: 8, revelationType: 'Meccan' },
  { id: 95, name: "التين", englishName: "At-Tin", versesCount: 8, revelationType: 'Meccan' },
  { id: 96, name: "العلق", englishName: "Al-Alaq", versesCount: 19, revelationType: 'Meccan' },
  { id: 97, name: "القدر", englishName: "Al-Qadr", versesCount: 5, revelationType: 'Meccan' },
  { id: 98, name: "البينة", englishName: "Al-Bayyinah", versesCount: 8, revelationType: 'Medinan' },
  { id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", versesCount: 8, revelationType: 'Medinan' },
  { id: 100, name: "العاديات", englishName: "Al-Adiyat", versesCount: 11, revelationType: 'Meccan' },
  { id: 101, name: "القارعة", englishName: "Al-Qari'ah", versesCount: 11, revelationType: 'Meccan' },
  { id: 102, name: "التكاثر", englishName: "At-Takathur", versesCount: 8, revelationType: 'Meccan' },
  { id: 103, name: "العصر", englishName: "Al-Asr", versesCount: 3, revelationType: 'Meccan' },
  { id: 104, name: "الهمزة", englishName: "Al-Humazah", versesCount: 9, revelationType: 'Meccan' },
  { id: 105, name: "الفيل", englishName: "Al-Fil", versesCount: 5, revelationType: 'Meccan' },
  { id: 106, name: "قريش", englishName: "Quraysh", versesCount: 4, revelationType: 'Meccan' },
  { id: 107, name: "الماعون", englishName: "Al-Ma'un", versesCount: 7, revelationType: 'Meccan' },
  { id: 108, name: "الكوثر", englishName: "Al-Kawthar", versesCount: 3, revelationType: 'Meccan' },
  { id: 109, name: "الكافرون", englishName: "Al-Kafirun", versesCount: 6, revelationType: 'Meccan' },
  { id: 110, name: "النصر", englishName: "An-Nasr", versesCount: 3, revelationType: 'Medinan' },
  { id: 111, name: "المسد", englishName: "Al-Masad", versesCount: 5, revelationType: 'Meccan' },
  { id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", versesCount: 4, revelationType: 'Meccan' },
  { id: 113, name: "الفلق", englishName: "Al-Falaq", versesCount: 5, revelationType: 'Meccan' },
  { id: 114, name: "الناس", englishName: "An-Nas", versesCount: 6, revelationType: 'Meccan' },
];

export const APP_THEME = {
  primary: 'emerald-700',
  secondary: 'amber-500',
  accent: 'slate-100',
};
